name: todo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.7.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter: 
    sdk: flutter
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.1.0
  get: ^4.1.4
  hive: ^2.0.2
  hive_flutter: ^1.0.0
  http: ^0.13.3
  path_provider: ^2.0.1
  uuid: ^3.0.3

dev_dependencies: 
  flutter_test: 
    sdk: flutter
  build_runner: ^1.12.2
  hive_generator: ^1.0.1

flutter: 
  uses-material-design: true

  assets:
    - assets/

